version: '3.9'

services:
  database:
    restart: always
    build: ./database
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: vanilla-node-server-database
    ports:
      - "5432:5432"
  server:
    restart: always
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: node index.js
    depends_on:
      - database