apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: vanilla-node-server_server
          imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
