CREATE TABLE lists (
	id INT GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE tasks (
	id INT GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	checked BOOLEAN NOT NULL,
	PRIMARY KEY(id),
	list_id INT,
	FOREIGN KEY(list_id)
		REFERENCES lists(id)
		ON DELETE CASCADE
);
