apiVersion: v1
kind: ConfigMap
metadata:
  name: database-secret
  labels:
    app: database
data:
  POSTGRES_DB: vanilla-node-server-database
  POSTGRES_PASSWORD: P@ssw0rd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: vanilla-node-server_database
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-secret
---
apiVersion: v1
kind: Service
metadata:
  name: database-clusterip
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - port: 5432
      nodePort: 30002
