name: CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run eslint
        run: yarn lint
      - name: Run tests
        run: yarn test
